  language: node_js

  node_js:
    - 10.16.0

  cache: yarn

  cash-directories:
    - ./client/node_modules
      ./server/node_modules

  before_script:
    - yarn run installAll

  script:
    - yarn run build ./client
