language: node_js
node_js:
  - "stable"
cash:
  yarn
  directories:
    - ./client/node_modules
      ./server/node_modules
before_script:
  - yarn run installAll
script:
  - yarn --cwd ./client run build

  
