  language: node_js

  node_js:
    - "stable"

  cash-directories:
    - ./client/node_modules
      ./server/node_modules

  before_script:
    - yarn run installAll

  script:
    - yarn run build ./client

    
